### ISSUE TITLE
Build Custom URL push

### ISSUE THREAD

**Issue by isaaclw** [danny0838/PyWebScrapBook#41]
I'm trying to figure out a way to push urls to my backend from my phone.

I found an app: https://play.google.com/store/apps/details?id=ch.rmy.android.http_shortcuts&hl=en_US&gl=US
But I'm having trouble setting up the http POST.

Could you walk me through what the payload needs to be assuming my url is: "www.google.com"?

I can't see it documented anywhere.

**Comment by danny0838** [comment]
I don't get it... What does "push urls to backend" and "setting up HTTP POST" mean?

**Comment by danny0838** [comment]
The web UI of the backend currently supports file management only. You can add, upload, edit, move, delete file, but scrapbook item management is currently not supported.

Scrapbook management can be done using the WSB extension. Unfortunately mobile support is currently not sufficient. Firefox for Android used to support it but currently not due to structure change, and we don't know when official support will come back... For using WSB extensions on Android, you can try Firefox for Android <= 68, or Kiwi or Yandex browser.

Currently there's no documentation for the API, as it's still under development and may change. If you do want to do that you may have to check the source code of PyWSB and WSB browser extension to see how they interact with each other.

We are considering making a web UI for scrapbook management, but sidebar support may be impossible due to the limitation of the browser framework...
