### ISSUE TITLE
Server doesn't support `Connection: Keep-Alive`

### ISSUE THREAD

**Issue by GarrisonBaird** [danny0838/PyWebScrapBook#9]
I'm deploying `wsb` on a remote server, and I found that the every HTTP request (every html/css/img) needs a new TCP connection, it takes seconds to finish loading a page.
I tried to add a reverse proxy in front of `wsb`, only one TCP connection is needed and page gets loaded instantly.

**Comment by danny0838** [comment]
WebScrapBook server is meant to provide a quick light-weight server for basic local hosting and personal usage rather than an omnipotent server. For production usage or when performance is a concern, install a more specialized server that supports modern features such as HTTP/2.0 or so and run WebScrapBook as a WSGI application.

Optimization of server is not our primary concern and expertise. If someone can improve the server with minor code reworking we'd be glad to implement it; otherwise it would be of rather lower priority.

**Comment by danny0838** [comment]
We are considering shifting current framework from **bottle** to **flask**, which seems to own a more robust ecosystem. Flask supports multi-threading and can be configured to use HTTP/1.1. A quick investigation suggests that it can support keep-alive.

There are still other options, such as frameworks based on asyncio. They are currently less preferable because:
1. They require ASGI, which is incompatible with WSGI. An ASGI application cannot be run on WSGI server, which would preclude some convenient servers such as mod_wsgi. On the other hand, an WSGI application can be run on an ASGI server with a wrapper like asgiref.
2. ASGI based applications/servers are generally newer and requires higher Python version such as 3.6+ or 3.7+. They are also less used and tested.
3. According to a quick benchmark, there is no significant performance difference among flask and ASGI based app/server (tested with starlette+uvicorn).

HTTP/2.0 can further improve performance for sure but is also not preferable as current browser implementation requires SSL, which is probably too cumbersome for local hosting.

Again, the built-in server is aim for quick local hosting and remote personal usage. For production usage opening to the world, a production server should be used.

Here's our current planning. Any idea is welcome.

**Comment by danny0838** [comment]
@GarrisonBaird We implemented Flask-based app which supports multi-threaded request handler. Could you try the [preview version](https://github.com/danny0838/PyWebScrapBook/tree/devel) and help confirm whether this issue is resolved or not?
